### ISSUE TITLE
Nesanica Ring missing latent effects.

### ISSUE THREAD

**Issue by Aeltorian** [CatsAndBoats/catseyexi#291]
[Bug Reports](https://discord.com/channels/696847769444548700/1192912334553890837)

[Looks like the latents are missing the Regen +1 and Regain +10 effect while sleeping. ](https://www.bg-wiki.com/ffxi/Nesanica_Ring)

**Comment by CatsEyeXI** [comment]
https://github.com/LandSandBoat/server/pull/5122
