### ISSUE TITLE
Ferroalloy Quadav does not have the correct loot pool.

### ISSUE THREAD

**Issue by Aeltorian** [CatsAndBoats/catseyexi#292]
[Bug Report](https://discord.com/channels/696847769444548700/1193060680522272778)

[Ferroalloy Quadav](https://www.bg-wiki.com/ffxi/Ferroalloy_Quadav) drops the wrong loot pool. There's 2 items that it drop in the bgwiki list.

**Comment by CatsEyeXI** [comment]
https://github.com/LandSandBoat/server/pull/5090
